-- Наполняем подсправочник продуктов --

insert into products (product, des, category_id) values ('Кофеварка', 'Рожковая', 2);
insert into products (product, des, category_id) values ('Кофеварка', 'Капельная', 2);
insert into products (product, des, category_id) values ('Кофеварка', 'Капсульная', 2);
insert into products (product, des, category_id) values ('СВЧ печь', 'СВЧ', 2);
insert into products (product, des, category_id) values ('Чайник', 'Стекло', 2);
insert into products (product, des, category_id) values ('Чайник', 'Пластик', 2);
insert into products (product, des, category_id) values ('Блендер', 'Набор', 2);
insert into products (product, des, category_id) values ('Мясорубка', 'Многофункциональный', 2);
insert into products (product, des, category_id) values ('ТВ', 'OLED', 1);
insert into products (product, des, category_id) values ('ТВ', 'QLED', 1);
insert into products (product, des, category_id) values ('Аудио-система', '5.1', 1);
insert into products (product, des, category_id) values ('Аудио-система', '7.1', 1);
insert into products (product, des, category_id) values ('Утюг', 'С парогенератором', 1);
insert into products (product, des, category_id) values ('Утюг', 'Без парогенератора', 1);
insert into products (product, des, category_id) values ('Пылесос', 'Мешковый', 1);
insert into products (product, des, category_id) values ('Пылесос', 'Безмешковый', 1);
insert into products (product, des, category_id) values ('Триммер', 'Проводной', 3);
insert into products (product, des, category_id) values ('Триммер', 'Безпроводной', 3);
insert into products (product, des, category_id) values ('Зубная щетка', 'Набор', 3);
insert into products (product, des, category_id) values ('Зубная щетка', 'Одна', 3);
insert into products (product, des, category_id) values ('Фен', 'Профессиональный', 3);
insert into products (product, des, category_id) values ('Фен', 'Набор', 3);
insert into products (product, des, category_id) values ('Стайлер', 'Набор', 3);
insert into products (product, des, category_id) values ('Смартфон', '4inch', 4);
insert into products (product, des, category_id) values ('Смартфон', '5inch', 4);
insert into products (product, des, category_id) values ('Колонка', '3Вт', 4);
insert into products (product, des, category_id) values ('Колонка', '5Вт', 4);
insert into products (product, des, category_id) values ('Смарт-часы', 'Резина', 4);
insert into products (product, des, category_id) values ('Смарт-часы', 'Текстиль', 4);
insert into products (product, des, category_id) values ('Фотоаппарат', 'Зеркальный', 4);
insert into products (product, des, category_id) values ('Фотоаппарат', 'Компактный', 4);
insert into products (product, des, category_id) values ('Пылесос', 'Вертикальный', 1);
insert into products (product, des, category_id) values ('Пылесос', 'Робот-пылесос', 1);
insert into products (product, des, category_id) values ('Увлажнитель', 'С очистителем', 1);
insert into products (product, des, category_id) values ('Обогреватель', 'Радиаторный', 1);
insert into products (product, des, category_id) values ('Электробритва', 'Роторная', 3);
insert into products (product, des, category_id) values ('Холодильник', '2 камеры', 2);
insert into products (product, des, category_id) values ('Холодильник', '1 камера', 2);
insert into products (product, des, category_id) values ('Стиральная машина', 'Встраиваемая', 2);
insert into products (product, des, category_id) values ('Стиральная машина', 'Компакт', 1);
insert into products (product, des, category_id) values ('Духовой шкаф', 'Встраиваемый', 2);
insert into products (product, des, category_id) values ('Духовой шкаф', 'Переносной', 1);
insert into products (product, des, category_id) values ('Принтер', 'Струйный', 4);
insert into products (product, des, category_id) values ('Принтер', 'Лазерный', 4);
insert into products (product, des, category_id) values ('Принтер', 'МФУ', 4);
insert into products (product, des, category_id) values ('Тостер', 'Черный', 2);
insert into products (product, des, category_id) values ('Тостер', 'Белый', 2);
insert into products (product, des, category_id) values ('Эпилятор', 'Набор', 3);
insert into products (product, des, category_id) values ('Машинка для стрижки', 'Набор', 3);
insert into products (product, des, category_id) values ('Мультиварка', 'Белая', 2);
insert into products (product, des, category_id) values ('ТВ', '4К', 1);
insert into products (product, des, category_id) values ('Монитор', '20inch', 4);
insert into products (product, des, category_id) values ('Монитор', '25inch', 4);
insert into products (product, des, category_id) values ('Планшет', '9inch', 4);
insert into products (product, des, category_id) values ('Светильник', 'LED', 1);
insert into products (product, des, category_id) values ('Светильник', '40ВТ', 1);
insert into products (product, des, category_id) values ('Светильник', '15ВТ', 1);
insert into products (product, des, category_id) values ('Кондиционер', 'Инвентор', 1);
insert into products (product, des, category_id) values ('Кондиционер', 'Напольный', 1);
insert into products (product, des, category_id) values ('Видеокамера', '4К', 4);
insert into products (product, des, category_id) values ('Видеокамера', 'FullHD', 4);


commit;
